### ISSUE TITLE
Can't make C library and examples without fortran 

### ISSUE THREAD

**Issue by chriscamacho** [schlatterbeck/pgapack#1]
I'm not sure at this point if fortran is a requirement for this library ?

Assuming that its possible just to use it with C, there doesn't seem to be any option in the makefile to switch of the fortran library compile and the fortran examples.

**Comment by schlatterbeck** [comment]
Thanks for the report.
Fortran is no requirement, so you can build for C only.
It may well be that it's currently impossible to build for C only. I'm not sure when I get around looking into this (as usual the last days before christmas are hectic). You may want to look into the makefile yourself and turn off the fortran stuff, then either make a full-fledged pull request or just attach your changed makefile to this issue and I'll take a look at it when time permits?

Ralf

**Comment by chriscamacho** [comment]
to be honest I couldn't see an easy way to do it, as I'm not familiar enough with the project and I'm in the process of evaluating a number of other libraries.  I may get chance at a later date.

**Comment by schlatterbeck** [comment]
I've now looked into the Makefile. It's as easy as specifying an empty fortran compiler on the command-line of make. So if you're building the serial version (without MPI) you would say
```
make MPI=serial FC=
```
I'll document this as time permits.

**Comment by schlatterbeck** [comment]
This is finally officially documented.
