### ISSUE TITLE
The same strings appears

### ISSUE THREAD

**Issue by wj314** [schlatterbeck/pgapack#11]
Hello,
I have used PGASetPopReplaceType(ctx,PGA_POPREPL_RTR) and PGASetNoDuplicatesFlag(ctx,PGA_TRUE), but I still output the same strings,like: (the first two numbers are iteration number and string order, the last five numbers are parameters to be optimized)
     7029        77    1.6057   11.8247    2.9348    7.1106    1.3480
     7029        78    1.6057   11.8247    2.9348    7.1106    1.3480

Additionally, I output the numbers by "%50.30f", and the float numbers seems to be "exactly" equal, like:
  38370        91                  1.630089342594146950560229925031                 12.925256848335266113281250000000                3.127193450927734375000000000000                  5.190304525911808575244776875479                  0.963786709308624311987045985006
     38370        92                  1.630089342594146950560229925031                 12.925256848335266113281250000000                  3.127193450927734375000000000000                  5.190304525911808575244776875479                  0.963786709308624311987045985006
     38370        93                  1.630089342594146950560229925031                 12.925256848335266113281250000000                  3.127193450927734375000000000000                  5.190304525911808575244776875479                  0.963786709308624311987045985006

So, how to avoid the same strings? Thanks.

**Comment by schlatterbeck** [comment]
Thanks for the report, as indicated in email previously this is a feature-interaction bug with RTR population replacement and duplicate avoidance. I can reproduce this with a modified version of examples/c/maxint.c, see latest commit for that file: When running this with, e.g., string length 5, 20 iterations and all other y/n questions answered with yes, the last generation before stopping (probably other generations, too, i've not investigated those) shows lots of duplicates. 

The same problem seems to exist for pairwise best replacement (usually used with differential evolution) but I've not yet added a test.

**Comment by schlatterbeck** [comment]
This is now fixed for the RTR population replacement but not yet for pairwise best. I'm planning to make the differential evolution method available for integer genes, too, so this will go with the changes necessary for this.

**Comment by wj314** [comment]
Thanks for your advice. I'll try the differential evolution method for my optimization.

**Comment by schlatterbeck** [comment]
I've now implemented differential evolution for integer genes and fixed the outstanding feature interaction bug with pairwise best replacement (the replacement type used with differential evolution) and duplicate avoidance.
