### ISSUE TITLE
Poor performance in parallel mode

### ISSUE THREAD

**Issue by fdmartins** [schlatterbeck/pgapack#2]
I compiled pgapack with **make MPI=openmpi** o ubuntu linux. And made a small change to the example maxint including a stop condition and len and maxiter as constants.

why performance using more than one process is worse than Sequential?

**$time ./examples/c/maxint**
real    0m1,863s
user    0m1,695s
sys     0m0,016s

**$time mpirun --use-hwthread-cpus ./examples/c/maxint**
real    0m2,592s
user    0m9,425s
sys     0m0,085s

**$time mpirun -np 4 ./examples/c/maxint**
real    0m3,137s
user    0m8,255s
sys     0m3,374s

```
lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Socket(s):           1
NUMA node(s):        1
Model name:          Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
NUMA node0 CPU(s):   0-3
```

Thank you!

**Comment by schlatterbeck** [comment]
The parallel mode works by sending the genes via a network. Each processor works on one gene and returns the evaluation value via network. Even if all processors are on the same CPU it will still involve the network stack and serialize/deserialize the data.
This means if the communication overhead is of the same order of magnitude (or even larger) than the evaluation function (which in the case of maxint is very small) the overhead will dominate and it will become slower than the serial version.

An example where the evaluation function is expensive (and where parallelizing with openmpi will bring a huge improvement) is antenna simulation, see my blog.runtux.com for an example.
Other evaluation functions that benefit from parallel execution are algorithms that involve finite element methods.

So it's not a bug -- it simply depends on how large the communication overhead is in relation to the computation time.

**Comment by fdmartins** [comment]
Hmm...it makes sense! thank you for the explanation! 

just for fun, I put a little bit of delay **usleep(1000)** in the evaluation  function 
and now the convergence was much faster using parallel mode.

```
$time mpirun -np 1 ./examples/c/maxint
real    1m31,151s
user    0m8,225s
sys     0m1,136s
```

```
$time mpirun -np 4 ./examples/c/maxint
real    0m20,305s
user    0m21,365s
sys     0m6,862s
```

```
time mpirun -np 10 ./examples/c/maxint
real    0m8,194s
user    0m10,152s
sys     0m6,857s
```

pgapack is amazing
Thank you!
